---
metallb_version: v0.13.5
metallb_yaml_url: "https://raw.githubusercontent.com/metallb/metallb/{{ metallb_version }}/config/manifests/metallb-native.yaml"
metallb_address_space: 192.168.205.200-192.168.205.210
